<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>OwHelper</AssemblyName>
    <RootNamespace>OwHelper</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OwHelper.App\OwHelper.App.csproj" />
    <ProjectReference Include="..\OwHelper.Core\OwHelper.Core.csproj" />
  </ItemGroup>

</Project>
