<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>BgKeyProbe</AssemblyName>
    <RootNamespace>BgKeyProbe</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OwHelper.Core\OwHelper.Core.csproj" />
  </ItemGroup>

</Project>
