<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>OwHelperStandIn</AssemblyName>
    <RootNamespace>OwHelper.TestSupport.StandIn</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
